FULL_NAMES = {
    "PKN": "orlen",
    "PZU": "pzu sa",
    "PKO": "pko bp",
    "PEO": "bank pekao",
    "KGH": "kghm",
    "JSW": "jsw",
    "LPP": "lpp",
    "CDR": "cd projekt",
    "ALR": "alior bank",
    "CPS": "cyfrowy polsat",
    "DNP": "dino",
    "EUR": "eurocash",
    "KTY": "kety",
    "LTS": "lotus",
    "MBK": "mbank",
    "OPL": "orange",
    "PGE": "pge",
    "PLY": "playway",
    "SPL": "santander",
    "TPE": "tauron",
    "ALE": "allegro",


    "AMC": "amica",
    "ASE": "asseco",
    "ATO": "alto",
    "BDX": "budimex",
    "BNP": "bnp paribas",
    "BRS": "benefit systems",
    "CIG": "ci games",
    "CMR": "comarch",
    "COG": "cognor",
    "DOM": "dom development",
    "ENA": "enea",
    "FMF": "famur",
    "FRO": "fera",
    "GTC": "gtc",
    "HBP": "hb polska",
    "ING": "ing",
    "KRU": "kruk",
    "LWB": "bogdanka",
    "MAB": "mabion",
    "MIL": "millennium",
    "MLB": "mlp group",
    "NEU": "neuca",
    "OAT": "oat",
    "PEP": "pepco",
    "R22": "r22",
    "RCH": "roch",
    "SEL": "selvita",
    "SKH": "skarb",
    "STP": "staporkow",
    "TEN": "ten square games",
    "TIM": "tim",
    "TSG": "tsg",
    "VOT": "voxel",
    "WPL": "wirtualna polska",
}
